# docker-compose.yml
version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=xiaoma
      - DATABASE_PASSWORD=AA98989595
      - DATABASE_NAME=xiaomatest
    depends_on:
      - database

  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: xiaoma
      POSTGRES_PASSWORD: AA98989595
      POSTGRES_DB: xiaomatest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
